trigger:
  branches:
    include:
      - master

pool:
  name: 'localhost'

variables:
  azureSubscription: 'rascals' # Update with your service connection name
  location: 'uksouth'                      # Default location, can be overridden
  env: 'dev'                                 # Environment name, can be overridden
  rgName: 'rascals-bicep-rg'                     # Resource group name, can be overridden
  bicepFile: 'infra/main.bicep'               # Path to your main Bicep file

steps:
- task: AzureCLI@2
  displayName: 'Deploy Bicep Infrastructure'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      Write-Host "Deploying Bicep template: $(bicepFile)"
      az deployment sub create `
        --location $(location) `
        --template-file $(bicepFile) `
        --parameters env=$(env) rgName=$(rgName) location=$(location)
